### ISSUE TITLE
Blank.saver for Catalina

### ISSUE THREAD

**Issue by dzwicker** [theseal/macos-blank-screensaver#2]
Macos 10.15 told me that the software Blank.saver can't be checked for malicious code and must be updated.

**Comment by theseal** [comment]
Which version of Blank do you use? I just upgraded to Catalina without any issues.

**Comment by dzwicker** [comment]
I have used homebrew to install it. Looks like I\m using 2.0.0

```
==> Satisfying dependencies
==> Downloading https://github.com/theseal/macos-blank-screensaver/archive/2.0.0.tar.gz
==> Downloading from https://codeload.github.com/theseal/macos-blank-screensaver/tar.gz/2.0.0
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'blank-screensaver'.
==> Uninstalling Cask blank-screensaver
==> Backing Screen Saver 'Blank.saver' up to '/usr/local/Caskroom/blank-screensaver/2.0.0/macos-blank-screensaver-2.0.0/Blank.saver'.
==> Removing Screen Saver '/Users/dzwicker/Library/Screen Savers/Blank.saver'.
==> Purging files for version 2.0.0 of Cask blank-screensaver
==> Installing Cask blank-screensaver
==> Moving Screen Saver 'Blank.saver' to '/Users/dzwicker/Library/Screen Savers/Blank.saver'.
🍺  blank-screensaver was successfully installed!
```
<img width="532" alt="Screenshot 2019-10-15 at 14 25 23" src="https://user-images.githubusercontent.com/500483/66831313-a327d280-ef57-11e9-8eab-f21996533478.png">

**Comment by theseal** [comment]
I guess that [Open a Mac app from an unidentified developer]( https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) could be a workaround but not a really good solution.

I can't reproduce this issue on my machine but will ask @simmel for input when he upgrade/re-install this work machine with Catalina.

**Comment by jdeluyck** [comment]
I can confirm this. It also no longer works for me on my device on Catalina.

**Comment by theseal** [comment]
Me as well can recreate the issue on a colleagues computer with Catalina. After confirming the issue we tried with the older version of Blank which is the file `Blank.qtz` in the repo. Not sure why but it seems like Apple added support for qtz screen savers again because it worked just fine.

Could you try it as well?

```
rm  -r ~/Library/Screen\ Savers/Blank.saver
cp Blank.qtz ~/Library/Screen\ Savers/
```

**Comment by jdeluyck** [comment]
> Could you try it as well?

Can confirm that this one does work. Oddly enough.
