### ISSUE TITLE
Does not work with Monterey

### ISSUE THREAD

**Issue by forthrin** [theseal/macos-blank-screensaver#8]
Do you have a target date for supporting later macOS versions?

Since upgrading macOS, I can't use this screen saver anymore, which is a major nuisance.

(I'll explain my use case if you're interested)!

```
You cannot use the Blank screen saver with this version of macOS.
Please contact the vendor to get a newer version of the screen saver.
```

See #3.

If anyone knows about alternative open source software to use, let me know.

**Comment by theseal** [comment]
It works just fine for me. Which version and installation method are you using?

**Comment by forthrin** [comment]
```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
$ git clone https://github.com/theseal/macos-blank-screensaver
$ cp Blank.qtz ~/Library/Screen\ Savers/
```

**Comment by theseal** [comment]
For Monterey you should use the `.saver` alternative.

The documentation isn't up to date but the homebrew tap is:
https://github.com/theseal/homebrew-blank-screensaver/blob/master/Casks/blank-screensaver.rb

**Comment by forthrin** [comment]
Works. Oh, the relief.

FYI: The reason I need a black screensaver, is because sleeping the display (A large Sony TV) displays some ugly "No connection" OSD text (which no living person wants in their living room) rather than displaying just blackness.
